import type { Metadata } from "next";
import Link from "next/link";
import { headers } from "next/headers";
import { notFound } from "next/navigation";
import { fetchPlanetProfile } from "@/lib/planet-profile";
import { resolveServerSiteOrigin } from "@/lib/site-url";

const ADDRESS_RE = /^0x[a-fA-F0-9]{40}$/;

const shortAddress = (address: string) => `${address.slice(0, 8)}…${address.slice(-6)}`;

export async function generateMetadata({ params }: { params: { address: string } }): Promise<Metadata> {
  const address = params.address.toLowerCase();
  const profile = ADDRESS_RE.test(address) ? await fetchPlanetProfile(address) : null;
  const label = profile?.name ?? shortAddress(address);
  const title = `${label} | EFP Atlas Planet`;
  const description = `Explore ${label} in EFP Atlas with live social graph stats.`;
  const h = headers();
  const origin = resolveServerSiteOrigin({
    host: h.get("x-forwarded-host") ?? h.get("host"),
    forwardedProto: h.get("x-forwarded-proto"),
  });
  const pageUrl = `${origin}/planet/${address}`;
  const imageUrl = `${origin}/planet/${address}/opengraph-image`;

  return {
    title,
    description,
    openGraph: {
      title,
      description,
      url: pageUrl,
      type: "website",
      images: [{ url: imageUrl }],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [imageUrl],
    },
  };
}

export default async function PlanetPage({ params }: { params: { address: string } }) {
  const address = params.address.toLowerCase();
  if (!ADDRESS_RE.test(address)) notFound();

  const profile = await fetchPlanetProfile(address);
  const label = profile?.name ?? shortAddress(address);

  return (
    <main style={{ minHeight: "100dvh", display: "grid", placeItems: "center", padding: 24, background: "radial-gradient(ellipse at 30% 20%, #0d1c3a 0%, #050a16 55%, #020508 100%)", color: "#e6f1ff", fontFamily: "'Space Grotesk', sans-serif" }}>
      <div style={{ width: "min(720px, 100%)", background: "rgba(11,22,40,0.85)", border: "1px solid rgba(0,212,255,0.2)", borderRadius: 20, padding: 24, backdropFilter: "blur(12px)" }}>
        <div style={{ fontFamily: "'IBM Plex Mono', monospace", color: "#67e8f9", fontSize: 12, letterSpacing: "0.08em" }}>EFP ATLAS · PLANET PROFILE</div>
        <h1 style={{ margin: "8px 0 6px", fontSize: 30 }}>{label}</h1>
        <div style={{ color: "#96a8c4", fontFamily: "'IBM Plex Mono', monospace", fontSize: 13 }}>{shortAddress(address)}</div>

        <div style={{ display: "grid", gridTemplateColumns: "repeat(3, minmax(0, 1fr))", gap: 10, marginTop: 20 }}>
          <Stat label="Followers" value={(profile?.followers ?? 0).toLocaleString()} />
          <Stat label="Following" value={(profile?.following ?? 0).toLocaleString()} />
          <Stat label="Score" value={Math.round(profile?.score ?? 0).toLocaleString()} />
        </div>

        <p style={{ marginTop: 16, color: "#9eb2d2", lineHeight: 1.55 }}>
          Share this URL on X to get a large preview card image generated by EFP Atlas.
        </p>

        <div style={{ marginTop: 18, display: "flex", gap: 10, flexWrap: "wrap" }}>
          <Link href="/" style={{ padding: "10px 14px", borderRadius: 10, border: "1px solid rgba(0,212,255,0.35)", color: "#67e8f9", textDecoration: "none", fontFamily: "'IBM Plex Mono', monospace", fontSize: 12 }}>
            ← Back To Atlas
          </Link>
          <a href={`https://efp.app/${profile?.name ?? address}`} target="_blank" rel="noreferrer" style={{ padding: "10px 14px", borderRadius: 10, border: "1px solid rgba(255,255,255,0.2)", color: "#dbeafe", textDecoration: "none", fontFamily: "'IBM Plex Mono', monospace", fontSize: 12 }}>
            View On EFP ↗
          </a>
        </div>
      </div>
    </main>
  );
}

function Stat({ label, value }: { label: string; value: string }) {
  return (
    <div style={{ border: "1px solid rgba(255,255,255,0.12)", borderRadius: 12, padding: "12px 10px", background: "rgba(255,255,255,0.03)" }}>
      <div style={{ color: "#67e8f9", fontFamily: "'IBM Plex Mono', monospace", fontWeight: 700 }}>{value}</div>
      <div style={{ color: "#97abc7", fontSize: 12, marginTop: 4 }}>{label}</div>
    </div>
  );
}
